// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(email string, isAdmin bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>PoolVibes - Pool Maintenance</title><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css\"><script type=\"module\" src=\"https://cdn.jsdelivr.net/gh/starfederation/datastar@v1.0.0-RC.7/bundles/datastar.js\"></script><style>\n\t\t\t\t[data-show] { display: none; }\n\t\t\t\t.tabs li.is-active a { border-bottom-color: #3273dc; color: #3273dc; }\n\t\t\t</style></head><body><div data-signals:tab=\"'chemistry'\" data-signals:_loading=\"false\" data-persist=\"tab\"><!-- Navbar --><nav class=\"navbar is-link\" role=\"navigation\"><div class=\"container\"><div class=\"navbar-brand\"><a class=\"navbar-item\" href=\"/\"><strong class=\"is-size-4\">PoolVibes</strong></a></div><div class=\"navbar-end\"><span class=\"navbar-item has-text-light\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(email)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/interface/web/templates/layout.templ`, Line: 28, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span><div class=\"navbar-item\"><form method=\"POST\" action=\"/logout\"><button type=\"submit\" class=\"button is-small is-light is-outlined\">Logout</button></form></div></div></div></nav><!-- Tab Navigation --><section class=\"section\" style=\"padding-bottom: 0;\"><div class=\"container\"><div class=\"tabs is-boxed is-medium\"><ul><li data-class:is-active=\"$tab === 'chemistry'\"><a data-on:click=\"$tab = 'chemistry'; @get('/chemistry')\">Water Chemistry</a></li><li data-class:is-active=\"$tab === 'tasks'\"><a data-on:click=\"$tab = 'tasks'; @get('/tasks')\">Tasks</a></li><li data-class:is-active=\"$tab === 'equipment'\"><a data-on:click=\"$tab = 'equipment'; @get('/equipment')\">Equipment</a></li><li data-class:is-active=\"$tab === 'chemicals'\"><a data-on:click=\"$tab = 'chemicals'; @get('/chemicals')\">Chemicals</a></li><li data-class:is-active=\"$tab === 'settings'\"><a data-on:click=\"$tab = 'settings'; @get('/settings')\">Settings</a></li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isAdmin {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<li data-class:is-active=\"$tab === 'admin'\"><a data-on:click=\"$tab = 'admin'; @get('/admin/users')\">Admin</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</ul></div></div></section><!-- Main Content --><section class=\"section\" style=\"padding-top: 1rem;\"><div class=\"container\"><div id=\"tab-content\" data-init=\"@get('/' + $tab)\"><div class=\"has-text-centered py-6 has-text-grey-light\">Loading...</div></div></div></section><!-- Modal Container --><div id=\"modal\"></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
